### ISSUE TITLE
File uploaded on S3 : strange file name

### ISSUE THREAD

**Issue by jongogogo** [awslabs/aws-config-rdk#11]
I am on Windows. Latest Python 3.6

From init: S3 bucket created: config-rule-code-bucket-XXXXXXXXX6564eu-west-1 (account id hidden) [note: why not putting an hyphen between the account id and region?]

I used the rdk deploy. The file uploaded directly in the bucket is named:
"emr-cmk-encrypted\emr-cmk-encrypted.zip"

I guess it supposes to have a directory, but not it is not created.
The CFn then failed with a "Error occurred while GetObject. S3 Error Code: NoSuchKey. S3 Error Message: The specified key does not exist."

Complete CFn logs:
07:53:35 UTC+0800 | ROLLBACK_COMPLETE | AWS::CloudFormation::Stack | emr-cmk-encrypted |  
-- | -- | -- | -- | --
  | 07:53:34 UTC+0800 | DELETE_COMPLETE | AWS::IAM::Role | rdkLambdaRole |  
  | 07:53:33 UTC+0800 | DELETE_IN_PROGRESS | AWS::IAM::Role | rdkLambdaRole |  
  | 07:53:32 UTC+0800 | DELETE_COMPLETE | AWS::Lambda::Function | rdkRuleCodeLambda |  
  | 07:53:10 UTC+0800 | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack | emr-cmk-encrypted | The following resource(s) failed to create: [rdkRuleCodeLambda]. . Rollback requested by user.
  | 07:53:10 UTC+0800 | CREATE_FAILED | AWS::Lambda::Function | rdkRuleCodeLambda | Error occurred while GetObject. S3 Error Code: NoSuchKey. S3 Error Message: The specified key does not exist.
  | 07:53:01 UTC+0800 | CREATE_IN_PROGRESS | AWS::Lambda::Function | rdkRuleCodeLambda |  
  | 07:52:59 UTC+0800 | CREATE_COMPLETE | AWS::IAM::Role | rdkLambdaRole |  
  | 07:52:42 UTC+0800 | CREATE_IN_PROGRESS | AWS::IAM::Role | rdkLambdaRole | Resource creation Initiated
  | 07:52:42 UTC+0800 | CREATE_IN_PROGRESS | AWS::IAM::Role | rdkLambdaRole |  
  | 07:52:38 UTC+0800 | CREATE_IN_PROGRESS | AWS::CloudFormation::Stack | emr-cmk-encrypted | User Initiated

**Comment by michaelborchert** [comment]
Can you post the exact rdk command you used and a directory listing of your working directory?

**Comment by jongogogo** [comment]
Recreated the error in another account

C:\Users\jrault\AppData\Local\Programs\Python\Python36\Scripts>python rdk init
Running init!
Found Config Recorder: Application-Account-Compliance-as-Code-ConfigurationRecorder-XXXXXXXXX6YTYG
Found Config Role: arn:aws:iam::XXXXXXXXX4688:role/service-role/AWSConfigRole-DO-NOT-DELETE
Found Bucket: centralized-config-XXXXXXXXX6564
Config Service is ON
Config setup complete.
Creating Code bucket config-rule-code-bucket-XXXXXXXXX4688eu-west-1

C:\Users\jrault\AppData\Local\Programs\Python\Python36\Scripts>python rdk create dummyrule --runtime python3.6 --resource-types AWS::EC2:Instances
Running create!
Local Rule files created.

 Directory of C:\Users\jrault\AppData\Local\Programs\Python\Python36\Scripts\dummyrule

01/28/2018  03:48 PM    <DIR>          .
01/28/2018  03:48 PM    <DIR>          ..
01/28/2018  03:47 PM               814 dummyrule.py
01/28/2018  03:48 PM               241 parameters.json
01/28/2018  03:47 PM             5,595 rule_util.py
               3 File(s)          6,650 bytes
               2 Dir(s)  191,469,015,040 bytes free

C:\Users\jrault\AppData\Local\Programs\Python\Python36\Scripts\dummyrule>more parameters.json
{
  "Parameters": {
    "RuleName": "dummyrule",
    "SourceRuntime": "python3.6",
    "CodeKey": "dummyrule.zip",
    "InputParameters": "{}",
    "SourceEvents": "AWS::EC2:Instances",
    "SourcePeriodic": "TwentyFour_Hours"
  }
}

(parameter.json is unchanged)

C:\Users\jrault\AppData\Local\Programs\Python\Python36\Scripts>python rdk deploy dummyrule
Running deploy!
Zipping dummyrule
Uploading dummyrule
Creating CloudFormation Stack for dummyrule
Waiting for CloudFormation stack operation to complete...
Waiting for CloudFormation stack operation to complete...
Waiting for CloudFormation stack operation to complete...
Waiting for CloudFormation stack operation to complete...
Waiting for CloudFormation stack operation to complete...
Waiting for CloudFormation stack operation to complete...
Waiting for CloudFormation stack operation to complete...
Waiting for CloudFormation stack operation to complete...
Waiting for CloudFormation stack operation to complete...
Config deploy complete.

2018-01-28 | Status | Type | Logical ID | Status Reason
-- | -- | -- | -- | --
15:52:40 UTC+0800 ROLLBACK_COMPLETE AWS::CloudFormation::Stack dummyrule         15:52:38 UTC+0800 DELETE_COMPLETE AWS::IAM::Role rdkLambdaRole         15:52:37 UTC+0800 DELETE_IN_PROGRESS AWS::IAM::Role rdkLambdaRole         15:52:36 UTC+0800 DELETE_COMPLETE AWS::Lambda::Function rdkRuleCodeLambda         15:52:23 UTC+0800 ROLLBACK_IN_PROGRESS AWS::CloudFormation::Stack dummyrule  The following resource(s) failed to create: [rdkRuleCodeLambda]. . Rollback requested by user.       15:52:22 UTC+0800 CREATE_FAILED AWS::Lambda::Function rdkRuleCodeLambda  Error occurred while GetObject. S3 Error Code: NoSuchKey. S3 Error Message: The specified key does not exist.       15:52:12 UTC+0800 CREATE_IN_PROGRESS AWS::Lambda::Function rdkRuleCodeLambda         15:52:09 UTC+0800 CREATE_COMPLETE AWS::IAM::Role rdkLambdaRole         15:51:52 UTC+0800 CREATE_IN_PROGRESS AWS::IAM::Role rdkLambdaRole  Resource creation Initiated       15:51:52 UTC+0800 CREATE_IN_PROGRESS AWS::IAM::Role rdkLambdaRole         15:51:49 UTC+0800 CREATE_IN_PROGRESS AWS::CloudFormation::Stack dummyrule  User Initiated |   | 15:52:40 UTC+0800 | ROLLBACK_COMPLETE | AWS::CloudFormation::Stack | dummyrule |   |   | 15:52:38 UTC+0800 | DELETE_COMPLETE | AWS::IAM::Role | rdkLambdaRole |   |   | 15:52:37 UTC+0800 | DELETE_IN_PROGRESS | AWS::IAM::Role | rdkLambdaRole |   |   | 15:52:36 UTC+0800 | DELETE_COMPLETE | AWS::Lambda::Function | rdkRuleCodeLambda |   |   | 15:52:23 UTC+0800 | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack | dummyrule | The following resource(s) failed to create: [rdkRuleCodeLambda]. . Rollback requested by user. |   | 15:52:22 UTC+0800 | CREATE_FAILED | AWS::Lambda::Function | rdkRuleCodeLambda | Error occurred while GetObject. S3 Error Code: NoSuchKey. S3 Error Message: The specified key does not exist. |   | 15:52:12 UTC+0800 | CREATE_IN_PROGRESS | AWS::Lambda::Function | rdkRuleCodeLambda |   |   | 15:52:09 UTC+0800 | CREATE_COMPLETE | AWS::IAM::Role | rdkLambdaRole |   |   | 15:51:52 UTC+0800 | CREATE_IN_PROGRESS | AWS::IAM::Role | rdkLambdaRole | Resource creation Initiated |   | 15:51:52 UTC+0800 | CREATE_IN_PROGRESS | AWS::IAM::Role | rdkLambdaRole |   |   | 15:51:49 UTC+0800 | CREATE_IN_PROGRESS | AWS::CloudFormation::Stack | dummyrule | User Initiated
  | 15:52:40 UTC+0800 | ROLLBACK_COMPLETE | AWS::CloudFormation::Stack | dummyrule |  
  | 15:52:38 UTC+0800 | DELETE_COMPLETE | AWS::IAM::Role | rdkLambdaRole |  
  | 15:52:37 UTC+0800 | DELETE_IN_PROGRESS | AWS::IAM::Role | rdkLambdaRole |  
  | 15:52:36 UTC+0800 | DELETE_COMPLETE | AWS::Lambda::Function | rdkRuleCodeLambda |  
  | 15:52:23 UTC+0800 | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack | dummyrule | The following resource(s) failed to create: [rdkRuleCodeLambda]. . Rollback requested by user.
  | 15:52:22 UTC+0800 | CREATE_FAILED | AWS::Lambda::Function | rdkRuleCodeLambda | Error occurred while GetObject. S3 Error Code: NoSuchKey. S3 Error Message: The specified key does not exist.
  | 15:52:12 UTC+0800 | CREATE_IN_PROGRESS | AWS::Lambda::Function | rdkRuleCodeLambda |  
  | 15:52:09 UTC+0800 | CREATE_COMPLETE | AWS::IAM::Role | rdkLambdaRole |  
  | 15:51:52 UTC+0800 | CREATE_IN_PROGRESS | AWS::IAM::Role | rdkLambdaRole | Resource creation Initiated
  | 15:51:52 UTC+0800 | CREATE_IN_PROGRESS | AWS::IAM::Role | rdkLambdaRole |  
  | 15:51:49 UTC+0800 | CREATE_IN_PROGRESS | AWS::CloudFormation::Stack | dummyrule | User Initiated


C:\Users\jrault\AppData\Local\Programs\Python\Python36\Scripts>aws s3 ls s3://config-rule-code-bucket-XXXXXXX4688eu-west-1
2018-01-28 15:51:45       3082 dummyrule\dummyrule.zip

Tried that too:
C:\Users\jrault\AppData\Local\Programs\Python\Python36\Scripts\dummyrule>python ../rdk deploy dummyrule
Running deploy!
Traceback (most recent call last):
  File "../rdk", line 32, in <module>
    return_val = my_rdk.process_command()
  File "C:\Users\jrault\AppData\Local\Programs\Python\Python36\lib\site-packages\rdk\rdk.py", line 50, in process_command
    exit_code = method_to_call()
  File "C:\Users\jrault\AppData\Local\Programs\Python\Python36\lib\site-packages\rdk\rdk.py", line 294, in deploy
    my_rule_params = self.__get_rule_parameters(rule_name)
  File "C:\Users\jrault\AppData\Local\Programs\Python\Python36\lib\site-packages\rdk\rdk.py", line 690, in __get_rule_parameters
    parameters_file = open(params_file_path, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jrault\\AppData\\Local\\Programs\\Python\\Python36\\Scripts\\dummyrule\\dummyrule\\parameters.json'

**Comment by michaelborchert** [comment]
Should be fixed now in the pypi version - was using the OS path separator for constructing the S3 key in the rdk code and hardcoding "/" in the CFN template.  Worked fine on mac/linux, but not Windows.  Am now forcing "/" so should work on any OS.
