### ISSUE TITLE
Add a "diff" function with the code template (python)

### ISSUE THREAD

**Issue by jongogogo** [awslabs/aws-config-rdk#119]
Goal: have a fast way to see if a rule code is or not leveraging the latest RDK template code.

If we consider:
-> Rule code
-> Template code

I'd suggest that:
-> the diff ignores new functions/class in the rule code
-> the diff ignores the content of evaluate_compliance and evaluate_parameter
-> the diff ignore the global variables

**Comment by bmorrissirromb** [comment]
I think the solution here is to use `aws-config-rdklib`, which was published about 2 years after this issue was opened. `rdklib` packages all the boilerplate code into a Lambda layer, which makes diffing the code a moot point.

Closing this one.
