### ISSUE TITLE
Support an "offline mode" for rdk init

### ISSUE THREAD

**Issue by erikpaasonen** [awslabs/aws-config-rdk#122]
We're evaluating using this RDK for developing the code for our AWS Config rules in a multi-account environment. We've already set up Config Aggregator outside of the RDK, so for example Config Recording is already enabled.

I'm unable to perform `rdk init` without it making changes in our AWS environment that would conflict with our existing centralized deployment. Would like to have the ability to run something like `rdk init -offline` so that it just sets up the local directory as an RDK working directory.

This feature would enable us to use RDK for generating the code of our custom AWS Config rules. We'd like to take advantage of the boilerplate code, especially as it is updated over time. Our use case doesn't include using the RDK for deployment to an AWS account.

**Comment by michaelborchert** [comment]
The current pip-installable version of the RDK actually no longer requires the working directory to be special in any way, if you have rdk installed you can run `rdk create` in any directory to generate the rule files.  I realize that's not made clear in the documentation at all, and will update the docs to remove the confusion!
