### ISSUE TITLE
remote rule cloudformation template error

### ISSUE THREAD

**Issue by mukavik** [awslabs/aws-config-rdk#127]
The cloud formation template being generated by the RDK fro deploying Config rules in satellite account is adding the following components which is throwing an error. 
".TrashdesiredInstanceType": {
      "Default": "default", 
      "MinLength": 1, 
      "Type": "String", 
      "Description": "Pass-through to required Input Parameter desiredInstanceType for Config Rule .Trash", 
      "ConstraintDescription": "This parameter is required."
    }

".TrashConfigRule": {
      "Type": "AWS::Config::ConfigRule",
      "Properties": {
        "Source": {
          "Owner": "CUSTOM_LAMBDA",
          "SourceDetails": [
            {
              "EventSource": "aws.config",
              "MessageType": "ConfigurationItemChangeNotification"
            }
          ],
          "SourceIdentifier": {
            "Fn::Sub": "arn:${AWS::Partition}:lambda:${AWS::Region}:${LambdaAccountId}:function:RDK-Rule-Function-.Trash"
          }
        }

When i remove this code, the formation works fine.

**Comment by mukavik** [comment]
Yes you are correct there are multiple directories names .Trash having parameters.josn files within them.

**Comment by bmorrissirromb** [comment]
Line 3345 of rdk.py:             
```
for obj_name in os.listdir("."):
```

Should probably become:
```
for obj_name in os.listdir("."):
    if f.startswith('.'):
        continue  # Skip hidden items
```
