### ISSUE TITLE
Config Lambda Error

### ISSUE THREAD

**Issue by mukavik** [awslabs/aws-config-rdk#128]
The Config Lambda deployed in the compliance account is throwing the following error when invoked:
\evaluate_compliance() takes 2 positional arguments but 3 were given: TypeError
Traceback (most recent call last):
File "/var/task/MyRule.py", line 288, in lambda_handler
compliance_result = evaluate_compliance(event, configuration_item, valid_rule_parameters)
TypeError: evaluate_compliance() takes 2 positional arguments but 3 were given

The boiler plate code as given by RDK is 
`def evaluate_compliance(event, configuration_item, valid_rule_parameters): `

The custom logic written by me is as following:
```
def evaluate_compliance(config_item, rule_parameters):
    if (config_item['resourceType'] != 'AWS::EC2::Instance'):
        return 'NOT_APPLICABLE'
    elif (config_item['configuration']['instanceType'] ==
            rule_parameters['desiredInstanceType']):
        return 'COMPLIANT'
    else:
        return 'NON_COMPLIANT'
```

**Comment by jongogogo** [comment]
Add the "event" in your custom code as first argument of your evaluate_compliance() function. Even if you don't use it, it is OK.

If you want to see example of rules: https://github.com/awslabs/aws-config-rules/

**Comment by jongogogo** [comment]
Closing, feel free to reopen.

**Comment by mukavik** [comment]
It worked. Thanks for the help.
