### ISSUE TITLE
RDK minimum permissions insufficient

### ISSUE THREAD

**Issue by Kaikj** [awslabs/aws-config-rdk#129]
Creation of CloudFormation resource fails with the following message when using the [minumum permissions](https://github.com/awslabs/aws-config-rdk/blob/master/policy/rdk-minimum-permissions.json) defined in the repo:

![permission denied](https://user-images.githubusercontent.com/6221857/48881377-098f9800-ee50-11e8-9d20-aaba2bc9dbd6.png)

Might have something to do the policy defined in [line 44](https://github.com/awslabs/aws-config-rdk/blob/master/policy/rdk-minimum-permissions.json#L44) onwards

**Comment by jongogogo** [comment]
Can you replace: 
https://github.com/awslabs/aws-config-rdk/blob/604cf7c626bc63bfa882d92ba5390ca937c66d6d/policy/rdk-minimum-permissions.json#L51
By:
`"Resource": ["arn:aws:iam::*:role/rdk/*"]`

**Comment by michaelborchert** [comment]
That's my plan.  I've replaced the codebuild Role in my automated testing with an updated minimum permissions JSON that collapses the last two permissions stanzas and uses the rdk/* resource, once that tests clean I will pull it into the awslabs repo.

**Comment by Kaikj** [comment]
@jongogogo Thanks! It works now.
@michaelborchert Noted. I'll go with the suggested solution in the mean time. Thanks!

**Comment by MarwaMezghani** [comment]
Hello, 

I faced the same problem, the solution of jongogogo should be pushed.

**Comment by michaelborchert** [comment]
Updated in latest release.  Thanks!
