### ISSUE TITLE
No sample CI found for AWS::ElasticLoadBalancing::LoadBalancer

### ISSUE THREAD

**Issue by guardbadger** [awslabs/aws-config-rdk#130]
I attempted to get a sample CI for AWS::ElasticLoadBalancing::LoadBalancer. The error message suggests I log an issue here.

```No sample CI found for AWS::ElasticLoadBalancing::LoadBalancer, even though it appears to be a supported CI.  Please log an issue at https://github.com/awslabs/aws-config-rdk.```

**Comment by michaelborchert** [comment]
Added sample CI for AWS::ElasticLoadbalancing::LoadBalancer in v0.4.
