### ISSUE TITLE
Lambda SourceEvents do not have a MessageType OversizedConfigurationItemChangeNotification

### ISSUE THREAD

**Issue by stratusjerry** [awslabs/aws-config-rdk#133]
Specifying "SourceEvents": "AWS::Lambda::Function" in parameters.json, the RDK generated Cloudformation Template creates an Event Source Message Type of ConfigurationItemChangeNotification but not an additional OversizedConfigurationItemChangeNotification Message Type. Should this be added by default? It is added by default when using the AWS Console and some AWS articles mention adding it:

https://docs.aws.amazon.com/config/latest/developerguide/evaluate-config_develop-rules_nodejs-sample.html

**Comment by stefanolczak** [comment]
I agree that is is really needed. Fix in #328

**Comment by jarrettandrulis** [comment]
Merged the fix, thanks for it @stefanolczak
