### ISSUE TITLE
RDK dont work in Windows

### ISSUE THREAD

**Issue by carlosalvessdev** [awslabs/aws-config-rdk#135]
after installing rdk (pip install rdk), but it does not execute. the app asks for another app to run.
follow the example below:

![install-rdk](https://user-images.githubusercontent.com/25306300/52076468-e1ba6000-2575-11e9-81d4-80d6f5d709d9.jpg)

![error-rdk](https://user-images.githubusercontent.com/25306300/52076309-8d16e500-2575-11e9-9233-ccf021e2b326.jpg)

**Comment by jongogogo** [comment]
Got an issue myself on this :)

The current workaround I got:
1) set an environment variable:
`rdk=C:\Users\jrault\AppData\Local\Programs\Python\Python36\Scripts`
2) from the cmd I call the rdk like this (for example the init command)
`python %rdk%\rdk init`

**Comment by carlosalvessdev** [comment]
Thank you
That way I was able to run the command in the CMD, but not in PowerShell.
Anyway, solved my problem.
Thank you again

**Comment by carlosalvessdev** [comment]
Thank you
That way I was able to run the command in the CMD, but not in PowerShell.
Anyway, solved my problem.
Thank you again

**Comment by kanagua** [comment]
I am facing the same issue. how did you resolve this?

**Comment by bmorrissirromb** [comment]
Clone `git clone https://github.com/awslabs/aws-config-rdk.git`, then run `python setup.py install` as Admin.
