### ISSUE TITLE
Timeline for next stage of maturity?

### ISSUE THREAD

**Issue by jongogogo** [awslabs/aws-config-rdk#136]
As per documentation, 
> this tool should be considered in "Open Beta".

What is the roadmap to get it to a more advanced maturity?

**Comment by MarwaMezghani** [comment]
Hello, 

I have the same question of @jongogogo , do you plan any release in the next days/weeks/months? 

Thank you.

**Comment by bmorrissirromb** [comment]
As of May 26, 2020, the 'Open Beta' language has been removed from the documentation. Considering this resolved and closing.
