### ISSUE TITLE
Windows: rdk logs

### ISSUE THREAD

**Issue by jongogogo** [awslabs/aws-config-rdk#14]
On windows, got the following error.

C:\Users\myname\AppData\Local\Programs\Python\Python36\Scripts>python rdk logs myrule
'stty' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "rdk", line 32, in <module>
    return_val = my_rdk.process_command()
  File "C:\Users\jrault\AppData\Local\Programs\Python\Python36\lib\site-packages\rdk\rdk.py", line 50, in process_command
    exit_code = method_to_call()
  File "C:\Users\jrault\AppData\Local\Programs\Python\Python36\lib\site-packages\rdk\rdk.py", line 564, in logs
    self.__print_log_event(event)
  File "C:\Users\jrault\AppData\Local\Programs\Python\Python36\lib\site-packages\rdk\rdk.py", line 629, in __print_log_event
    rows, columns = os.popen('stty size', 'r').read().split()
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by jongogogo** [comment]
It is possible to get the log now from windows CMD (running as admin). But the following error appears before/after every line:
'stty' is not recognized as an internal or external command,
operable program or batch file.
Using default terminal rows and columns.

**Comment by bmorrissirromb** [comment]
These are the lines in rdk.py that are causing the issue. 
```
        try:
            rows, columns = os.popen("stty size", "r").read().split()
        except ValueError as e:
            # This was probably being run in a headless test environment which had no stty.
            print("Using default terminal rows and columns.")
```

Windows doesn't like this, since `stty` is a Linux binary. The solution should be a check that looks for the presence of `stty` first. Something like the following should resolve this.

```
from shutil import which
...
        if which("stty") is not None:
            try:
                rows, columns = os.popen("stty size", "r").read().split()
            except Exception as e:
                # This was probably being run in a headless test environment which had no stty.
                logging.warning("Using default terminal rows and columns.")
        else:
            logging.info("stty not present -- using default terminal rows and columns.")
```
