### ISSUE TITLE
Failed to create aws managed rule with rdk CLI

### ISSUE THREAD

**Issue by MarwaMezghani** [awslabs/aws-config-rdk#140]
Hello, 
I faced an issue while trying to activate AWS Managed Rule in Config using rdk CLI. 
I tryed : rdk create RDK-Managed-Rule --source-identifier S3_BUCKET_VERSIONING_ENABLED -R python3.6 -r AWS::S3::Bucket -m TwentyFour_Hours 
I had this error : rdk create: error: argument -R/--runtime: not allowed with argument --source-identifier
I removed the runtime value, it worked, but when I typed rdk deploy RDK-Managed-Rule I had this error : 
 
Traceback (most recent call last):
  File "/usr/bin/rdk", line 33, in <module>
    return_val = my_rdk.process_command()
  File "/usr/lib/python3.6/site-packages/rdk/rdk.py", line 68, in process_command
    exit_code = method_to_call()
  File "/usr/lib/python3.6/site-packages/rdk/rdk.py", line 736, in deploy
    'CAPABILITY_IAM',
  File "/usr/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python3.6/site-packages/botocore/client.py", line 634, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/usr/lib/python3.6/site-packages/botocore/client.py", line 682, in _convert_to_request_dict
    api_params, operation_model)
  File "/usr/lib/python3.6/site-packages/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter Parameters[3].ParameterValue, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
Invalid type for parameter Parameters[7].ParameterValue, value: None, type: <class 'NoneType'>, valid types: <class 'str'>

It seems that runtime value is mandatory because I checked rdk.py containing.

**Comment by jongogogo** [comment]
The managed rule S3_BUCKET_VERSIONING_ENABLED is a configuration change trigger rule ([ref](https://docs.aws.amazon.com/config/latest/developerguide/s3-bucket-versioning-enabled.html)). In the command which fails to deploy, you added a periodic trigger (`-m TwentyFour_Hours`).

Command to create this rule:
`rdk create RDK-Managed-Rule --source-identifier S3_BUCKET_VERSIONING_ENABLED -r AWS::S3::Bucket`

**Comment by michaelborchert** [comment]
@MarwaMezghani Did @jongogogo's comment resolve your issue?

**Comment by MarwaMezghani** [comment]
Yes @michaelborchert Thank you, and @jongogogo thank you for the answer, I didn't check that point before.
