### ISSUE TITLE
Add support for Python 3.7

### ISSUE THREAD

**Issue by mbeacom** [awslabs/aws-config-rdk#151]
AWS Lambda now supports Python 3.7 - it would be great for `rdk` to support it as well!

Thanks for your work on this project!
PR to come

**Comment by michaelborchert** [comment]
Thanks for the PR!  Sorry for the delay!

**Comment by mbeacom** [comment]
@michaelborchert All good - Thanks for merging!  Do you happen to have a roadmap for this project?  Any tasks I can pick up?
