### ISSUE TITLE
Scope of changes: All changes

### ISSUE THREAD

**Issue by linasslepikas** [awslabs/aws-config-rdk#157]
Hi, can not find a way to trigger custom rule on all changes in all recources. AWS console has option "All changes", how to get same result with rdk?

**Comment by rafihm** [comment]
@linasslepikas Currently rdk doesn't support creating a rule which triggers for "All Changes",
it only supports specific resource type.

**Comment by gdhgdhgdh** [comment]
That's a shame. Is this likely to be picked up as a future improvement?

My use case is 'anything which exists outside of eu-west-2 is non-compliant' so my Python would blindly return `NONCOMPLIANT` for every incoming CI.
