### ISSUE TITLE
Version 0.4.3 installed, but python 3.7 create rule not available

### ISSUE THREAD

**Issue by evannadeau** [awslabs/aws-config-rdk#171]

**Comment by evannadeau** [comment]
`PS C:\DEV\TC-AWS\TC-AWS_CorePipelines\rdk> rdk -v
rdk 0.4.3`

`-R {nodejs4.3,java8,python2.7,python3.6,dotnetcore1.0,dotnetcore2.0}, --runtime {nodejs4.3,java8,python2.7,python3.6,dotnetcore1.0,dotnetcore2.0}`

**Comment by rafihm** [comment]
@evannadeau The rdk version available on pypi repo doesn't have the support for python3.7
However, you can install it from the source if you would like to use python3.7.

To install from the source:
1. clone the repo `git clone https://github.com/awslabs/aws-config-rdk.git`
2. Install from the cloned dir `pip install ./aws-config-rdk/`


@michaelborchert Can we add the latest version of rdk to pypi ?
