### ISSUE TITLE
Keep recordingGroup configuration on rdk init

### ISSUE THREAD

**Issue by siulpolb** [awslabs/aws-config-rdk#178]
On rdk init the recording group configuration allways is setup with allSupported and includeGlobalResourceTypes set to True.
For existing multi-region, multi-account setup will be better to keep the exiting configuration and use the allSupported and includeGlobalResourceTypes on True as default values

**Comment by bmorrissirromb** [comment]
See also #436

**Comment by bmorrissirromb** [comment]
Closed by #436
