### ISSUE TITLE
add support for auto remediation

### ISSUE THREAD

**Issue by jack1902** [awslabs/aws-config-rdk#191]
Currently, I can't see a way to use auto-remediation with the RDK. Whilst the RDK is proving useful to develop rules, it is lacking a way to add auto-remediation of resources that become non-compliant

**Comment by cpaces** [comment]
Agree with @jack1902 . Perhaps as an intermediary solution is by adding some options to output rule ARN. This is to allow it to be chained in a CI/CD pipeline until better solution is in place.

**Comment by jack1902** [comment]
> Agree with @jack1902 . Perhaps as an intermediary solution is by adding some options to output rule ARN. This is to allow it to be chained in a CI/CD pipeline until better solution is in place.

Just looking at this a bit more now, I am curious as to why Jinja2 wasn't used for creating the Cloudformation for this as the template for cloudformation is all inline currently, will see if I can just add a new part to the code to output the rule_arn

**Comment by michaelborchert** [comment]
Thanks for the feedback!  Remediation support in RDK is being tested now, changes will probably be merged in later today and pushed out to pypi this week.
