### ISSUE TITLE
Bug in code for Rule with trigger type "Configuration changes"

### ISSUE THREAD

**Issue by ashishpujari** [awslabs/aws-config-rdk#192]
I noticed that the CF template generated for deployment of a rule with trigger type of "Configuration changes" specifies a SourceDetail of only type i.e. "ConfigurationItemChangeNotification"
According to Source - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-config-configrule-source-sourcedetails.html
"If you want your custom rule to be triggered by configuration changes, specify two SourceDetail objects, one for ConfigurationItemChangeNotification and one for OversizedConfigurationItemChangeNotification."

**Comment by jack1902** [comment]
Are you referring to the configRile.json within the template folder, or something else?

**Comment by ashishpujari** [comment]
Yes the configRule.json file needs to be updated to include both ConfigurationItemChangeNotification and OversizedConfigurationItemChangeNotification

**Comment by jarrettandrulis** [comment]
Fixed
