### ISSUE TITLE
Bucket name to store config snapshots can be specified in RDK

### ISSUE THREAD

**Issue by henrysher** [awslabs/aws-config-rdk#2]
Now it is hardcoded in RDK for the format of bucket name: config-bucket-<ACCOUNT_ID>. It is better if users can specified in config files or CLI parameters.

**Comment by michaelborchert** [comment]
Since this issue was logged against version one, is it still a problem?  RDK currently creates a bucket for each region that you need to deploy to.  What's the use case for custom bucket names?
