### ISSUE TITLE
Rules can't be created with trigger and periodic invocation

### ISSUE THREAD

**Issue by dnorth98** [awslabs/aws-config-rdk#20]
I may be missing something but

In the config rule console, I can create a rule that is triggered AND periodic (ie. the options are not mutually exclusive).  However, when I deploy a rule using the rdk, it doesn't seem to set both options even though my parameters file contains both periodic and source events.

```
{
  "Parameters": {
    "CodeKey": "access-key-rotation.zip", 
    "SourceRuntime": "python2.7", 
    "SourcePeriodic": "TwentyFour_Hours", 
    "RuleName": "access-key-rotation", 
    "SourceEvents": "AWS::IAM::User", 
    "InputParameters": "{\"maxKeyDays\": \"90\"}"
  }
}
```

I was hoping this would give me a rule triggered on users AND every 24 hours periodic.  Right now, I have to deploy using the rdk and then go into the UI and check off periodic to get both.

Am I missing something though?

**Comment by michaelborchert** [comment]
I don't think you're missing anything, this is something I need to address in the CFN template used to deploy the rule.  I'll take a look and push something out in the next few days.

**Comment by dnorth98** [comment]
That would be fantastic.  For now, I just over-rode it in the console but would be good to have this all in the CFN

**Comment by michaelborchert** [comment]
We had a debate about this with the service team, and ultimately decided that the best practice is to not have a single rule that handles both periodic and event-driven logic in the same rule.  From conversations with other customers and users, the amount of additional complexity makes testing to make sure your rule is doing what you want it to a lot harder and there's a higher risk that you won't have the compliance assurance that you think you do.  Closing this issue, but if you disagree strongly I'm happy to have the conversation.

**Comment by michaelborchert** [comment]
Reopening, as it turns out this approach is (ironically) incompatible with supporting deployment of Managed Rules.

**Comment by michaelborchert** [comment]
This has now been added by PR #81, and pushed to PyPi.  Thanks!
