### ISSUE TITLE
rdk --help should shows a list of commands available

### ISSUE THREAD

**Issue by kpx-dev** [awslabs/aws-config-rdk#206]
```
$ rdk --help
usage: rdk [-h] [-p PROFILE] [-k ACCESS_KEY_ID] [-s SECRET_ACCESS_KEY]
           [-r REGION] [-v]
           <command> ...

The RDK is a command-line utility for authoring, deploying, and testing custom
AWS Config rules.

positional arguments:
  <command>             Command to run. Refer to the usage instructions for
                        each command for more details
  <command arguments>   Run `rdk <command> --help` to see command-specific
                        arguments.
```

This is not helpful, I need to refer to doc or code to know what are the available commands.

**Comment by JohnVonNeumann** [comment]
Yo, I was about to file this issue myself but I'll just post my piece here.

I agree with the sentiments of @kienpham2000, the `rdk --help` command output is useless. The posarg doc states:

```
<command>             Command to run. Refer to the usage instructions for
                                  each command for more details
```

But there are no usage docs, and if there are, no indication of where these can be viewed. 

As a workaround, I use `rdk usage` to error and tell me what the options are, but this is not a legit way of handling it.

**Comment by jack1902** [comment]
Does this assist? Added some stuff to the help command to list out the available commands. If so, i can open a PR
<img width="1081" alt="listed_args" src="https://user-images.githubusercontent.com/39212456/71691931-85247e00-2da0-11ea-8ed8-1b851f8e2386.png">

**Comment by kienpham2000** [comment]
@jack1902 git and docker cli are good example of how to handle help correctly.

**Comment by managedkaos** [comment]
bumping this one 👍 

this output from `rdk --help` is not helpful because the options for `<command>` are not included:
```
  <command arguments>   Run `rdk <command> --help` to see command-specific arguments.
```

For the folks that come across this issue looking for all the commands, try this:
```
rdk foobar --help
```

You should see the following output:
```
usage: rdk [-h] [-p PROFILE] [-k ACCESS_KEY_ID] [-s SECRET_ACCESS_KEY] [-r REGION] [-v] <command> ...
rdk: error: argument <command>: invalid choice: 'foo' (choose from 'clean', 'create', 'create-rule-template', 'deploy', 'init', 'logs', 'modify', 'rulesets', 'sample-ci', 'test-local', 'undeploy', 'export')
```

Giving the following as the supported commands (sorted):

- `clean`
- `create`
- `create-rule-template`
- `deploy`
- `export`
- `init`
- `logs`
- `modify`
- `rulesets`
- `sample-ci`
- `test-local`
- `undeploy`
