### ISSUE TITLE
Cannot create config-role again

### ISSUE THREAD

**Issue by marcgardiner** [awslabs/aws-config-rdk#207]
### Environment:
- runtime: Python 3.7
- OS: Ubuntu 16.04

### What I faced:
- Problem Story
I deployed several config rules through RDK cli, by commands - init, create, modify, and deploy, and it worked well.
But for some reason, i deleted all stacks deployed through RDK sdk through AWS console, even role "config-role".
I ran command init again, but the role didn't create exactly, but output said that the role discovered.

![issue](https://user-images.githubusercontent.com/26286852/67583084-3f3eae80-f78e-11e9-8867-70e4a80e5863.png)

### What I expected:
Initialisation works properly by creating role.

**Comment by jack1902** [comment]
Those two Found Config * come from rdk/rdk.py lines 309 -> 314. 

```python
if len(recorders['ConfigurationRecorders']) > 0:
    config_recorder_exists = True
    config_recorder_name = recorders['ConfigurationRecorders'][0]['name']
    config_role_arn = recorders['ConfigurationRecorders'][0]['roleARN']
    print("Found Config Recorder: " + config_recorder_name)
    print("Found Config Role: " + config_role_arn)
```

do you have an existing config recorder in your account? You can check it in the console or via the aws cli using:

```sh
aws configservice describe-configuration-recorders
```
Source:
https://docs.aws.amazon.com/cli/latest/reference/configservice/describe-configuration-recorders.html

Can you post the output for this?
