### ISSUE TITLE
[Bug] Crash when "ResourceDeleted"

### ISSUE THREAD

**Issue by jongogogo** [awslabs/aws-config-rdk#21]
After building a ConfigurationChange-triggered rule, the wrapper crashes when the resource is deleted (no error in the log). It doesn't even get to the handler code (printing "event()").

Attached a code of a rule which crashes on IAM User.
[iam-mfa-enabled.txt](https://github.com/awslabs/aws-config-rdk/files/1750218/iam-mfa-enabled.txt)

**Comment by michaelborchert** [comment]
It looks like if a configuration event was failing the "is_applicable()" check it was not properly creating a "NOT_APPLICABLE" configuration response.  Has been updated for both Python runtimes and pushed to pypi.
