### ISSUE TITLE
ReadTheDocs Documentation points to wrong repo

### ISSUE THREAD

**Issue by jack1902** [awslabs/aws-config-rdk#218]
Currently, when i go to [ReadTheDocs](https://rdk.readthedocs.io/en/latest/), the edit on github button points to:

https://github.com/michaelborchert/aws-config-rdk/blob/master/docs/index.rst

**Expected behaviour**
I expected it to point to the master branch for [awslabs/aws-config-rdk](https://github.com/awslabs/aws-config-rdk), not a fork of it

**Comment by PodioSpaz** [comment]
Hello,

Are there any plans on updating [Read the Docs](https://rdk.readthedocs.io/en/latest/) to reference to correct repository?

`python3.8` still isn't listed as a valid runtime choice in the documentation.

Thanks

**Comment by PodioSpaz** [comment]
As a workaround, I'll keep [this](https://the-unofficial-rdk-documentation.readthedocs.io/en/latest/index.html) up-to-date with the latest release; until this ticket is closed.
