### ISSUE TITLE
Support uploading code to ONE bucket

### ISSUE THREAD

**Issue by jack1902** [awslabs/aws-config-rdk#228]
## background

Currently, to have multi region deployments of custom config rules, one must have a bucket for each region and have the code uploaded there. 

This is undesirable as the cost upload is multiplied by each bucket

## desired change
The ability to upload code ONCE and have it used in multiple regions as S3 is a global service

**Comment by bmorrissirromb** [comment]
Is this issue not solved by using...

`rdk init --skip-code-bucket-creation`

and

`rdk deploy --custom-code-bucket <your singular bucket>`?

Seems like this can be accomplished today.
