### ISSUE TITLE
TemplateURL on deploy is not working for eu-west-2

### ISSUE THREAD

**Issue by jack1902** [awslabs/aws-config-rdk#229]
### Description

When i run `rdk deploy --functions-only --all` the command errors out when attempting to create the `Stack`. This is due to the object URL for the `CloudFormation template`, being incorrect.

As noted in #93 and #120 , `--region all` isn't a thing neither is `--region` hence the initial `export` of an environment variable

### Steps to reproduce

1. Set region `export AWS_DEFAULT_REGION=eu-west-2` 
2. Run `rdk init`
3. Run `rdk create test --runtime python3.7 -m One_Hour`
4. Run `rdk deploy --functions-only --all` and observe errors

## Desired Change

The correct URL for the `CloudFormation template` be passed through to CloudFormation

**Comment by jack1902** [comment]
Found a workaround which seems horrible, but its a well documented issue with S3.

```
import botocore # Add this to imports

config = my_s3_client._client_config
            config.signature_version = botocore.UNSIGNED
template_url = boto3.client('s3', config=config).generate_presigned_url('get_object', ExpiresIn=0, Params={'Bucket': code_bucket_name, 'Key': self.args.stack_name + ".json"})
```

Source:
https://stackoverflow.com/questions/33809592/upload-to-amazon-s3-using-boto3-and-return-public-url

**Comment by rickychau2780** [comment]
@jack1902 can you paste the error? I am not able to reproduce the error. It works fine for me.
