### ISSUE TITLE
In Python templates parameter evaluation happens before event filtering

### ISSUE THREAD

**Issue by mikn-dragon** [awslabs/aws-config-rdk#244]
Example: https://github.com/awslabs/aws-config-rdk/blob/master/rdk/template/runtime/python3.7/rule_code.py#L312-L321

This may lead errors being raised for events that are irrelevant for the rule. I would suggest putting the parameter evaluation after the event evaluation to ensure that the errors being raised are only for events the lambda is interested in.

If you think this is a valuable change, I can open a PR!

Thanks :)

**Comment by chrgut** [comment]
Parameters could be used to control filtering logic so they should be processed/validated ahead of it.

**Comment by bmorrissirromb** [comment]
I'm going to close this based on the rationale that was provided about parameters controlling the filtering logic. If you would like to discuss further, feel free to reopen this!
