### ISSUE TITLE
No sample CI found for AWS::EC2::NatGateway

### ISSUE THREAD

**Issue by theksi** [awslabs/aws-config-rdk#251]
Hello,
Working on my first rule using `rdk 0.7.6`, I wanted to try an easy one (No Nat Gateway allowed).
I encountered an issue while trying to fetch a sample CI 

```shell
rdk sample-ci AWS::EC2::NatGateway
No sample CI found for AWS::EC2::NatGateway, even though it appears to be a supported CI.  Please log an issue at https://github.com/awslabs/aws-config-rdk.
```

**Comment by Leectan** [comment]
Having same issue with many other services. Wonder how I can escalate this. No official answers from AWS team have been found.

**Comment by rmcdonough** [comment]
+1 here, would very much like the same
