### ISSUE TITLE
[rdk create-template/deploy] Add parameters for the lambda timeout and concurency

### ISSUE THREAD

**Issue by jongogogo** [awslabs/aws-config-rdk#254]

**Comment by aredmond** [comment]
As of now the lambda timeout value is hardcoded to 300. https://github.com/awslabs/aws-config-rdk/blob/45882f82cbbb75392e4144e3cd6663f51cb75eab/rdk/rdk.py#L2887 

It would be great if this was bumped to the new max of 900 seconds or if this was exposed as a parameter. I am currently running into an issue with an RDS remediation that is occasionally going over 300 seconds.
