### ISSUE TITLE
rdk init fails after upgrade

### ISSUE THREAD

**Issue by indukuri1** [awslabs/aws-config-rdk#26]
The message that comes is as under
Traceback (most recent call last):
  File "/usr/local/bin/rdk", line 12, in <module>
    from rdk import rdk
  File "/Library/Python/2.7/site-packages/rdk/rdk.py", line 31, in <module>
    import mock
ImportError: No module named mock

**Comment by michaelborchert** [comment]
After some digging, it looks like we ran into a known pip edge case that caused the "mock" package requirement to not get installed properly: https://github.com/pypa/pip/issues/4780.  I'm working on a fix now, but in the meantime if you `pip install mock` I believe that should take care of it.  Or switch to a virtualenv and python 3. :)

**Comment by rafihm** [comment]
I think we don't have "mock" in "install_requires" section of the "setup.py".
can we Include "mock" to fix this issue ?

**Comment by michaelborchert** [comment]
Yes, I believe just doing a `pip install mock` will resolve the immediate
issue.

**Comment by michaelborchert** [comment]
`mock` is now present in the correct section of setup.py, closing the issue.
