### ISSUE TITLE
Returning a list:'evaluations' with compliance and annotation appended as a dictionary results in an error.

### ISSUE THREAD

**Issue by anthderr** [awslabs/aws-config-rdk#27]
Code Snippet:

```
if mfa_device_details['MFADevices'] == []:
            print('User: '+userName+' is NOT-COMPLIANT!')
            eval["ComplianceType"] = "NON_COMPLIANT"
            eval["Annotation"] = "No MFA Device detected for user"
            evaluation.append(eval)
            return evaluation
```

ERROR:
Parameter validation failed:
Invalid type for parameter Evaluations[0].ComplianceType, value: [{'ComplianceType': 'COMPLIANT', 'Annotation': ' MFA detected'}], type: <class 'list'>, valid types: <class 'str'>: ParamValidationError

We narrowed down the cause of this error to these lines in rule_util.py:

```
        configurationItem = get_configuration_item(invokingEvent)

        if configurationItem is None:
            compliance = lambda_handler(event, context)

            if isinstance(compliance, list):
                for evaluation in compliance:
                    missing_fields = False

```

The value returned from lambda_handler is compared to be a list only if configurationItem is None.
Version-runtime : rdk-0.3.7-py3.6

**Comment by michaelborchert** [comment]
This should be addressed now in the latest version for both Python runtimes and Node.
