### ISSUE TITLE
Feature inquiry: Export to Cloudformation

### ISSUE THREAD

**Issue by yoanisgil** [awslabs/aws-config-rdk#271]
Hi All,

I was just wondering if something like:

```
rdk export -f cloudformation
```

is feature that could make it to the master branch?

**Comment by RobReus** [comment]
There already is an option to create CloudFormation templates using RDK, see `rdk create-rule-template --help`. Is this what you mean? If not, could you elaborate further?

**Comment by yoanisgil** [comment]
I was referring to exporting an existing rule as a Cloudformation template. Right now `rdk export` only supports exporting to terraform.

**Comment by RobReus** [comment]
> I was referring to exporting an existing rule as a Cloudformation template. Right now `rdk export` only supports exporting to terraform.

My point is, the equivalent of `rdk export -f terraform` is `rdk create-rule-template`. The `export` command generates Terraform code, the `create-rule-template` command generates CloudFormation code. In the end they both do the exact same thing, only for different kind of IaC tools.

Is this what you want/need? If so, feel free to close this issue.

**Comment by yoanisgil** [comment]
Oh I see what you mean. You're right.
