### ISSUE TITLE
NO sample CI for AWS::CodeBuild::Project

### ISSUE THREAD

**Issue by ManuelUgarte** [awslabs/aws-config-rdk#304]
Hello, just creating an issue in regards to there not being a sample CI for AWS::CodeBuild::Project even though it appears to be a supported CI.

**Comment by sduguay-apttech** [comment]
It seems there's a lot of sample CI missing in there unfortunately.

**Comment by sduguay-apttech** [comment]
Small workaround for this use case. If you open the CLI and you run aws codebuild batch-get-projects --names "<projectname>" you will get the project structure you are looking for, assuming you already have at least a codebuild project.
