### ISSUE TITLE
feature request: single stack resources limit as number of rules grows

### ISSUE THREAD

**Issue by starchx** [awslabs/aws-config-rdk#313]
CloudFormation has following limits:

- Maximum number of resources that you can declare in your AWS CloudFormation template: 500 resources
- Maximum number of parameters that you can declare in your AWS CloudFormation template: 200 parameters
- Maximum size of a template body that you can pass in an Amazon S3 object: 1MB

As the number of rules grows, the single stack may not fit all the resources. Is there any recommended solution/workaround? Ideally not using nested stack, because we are deploying the templates via StackSet to multiple accounts and StackSet does not support deploying nested stack.

**Comment by bmorrissirromb** [comment]
RDK's behavior is to deploy a new stack for each rule. The limits described above should not impact RDK-deployed rules, as new rules do not get added to a stack, but rather get deployed in a new stack entirely.

Closing -- feel free to reopen if you have additional concerns!
