### ISSUE TITLE
Sample CI for AWS::ApiGatewayV2::Stage

### ISSUE THREAD

**Issue by bmccraw86** [awslabs/aws-config-rdk#339]
No sample CI found for AWS::ApiGatewayV2::Stage, even though it appears to be a supported CI.

**Comment by bmccraw86** [comment]
Looking at the `master` branch and I see the `AWS::ApiGatewayV2::Stage` example_ci file, but the deployed version of `rdk` doesn't seem to have it. I'm assuming this will be fixed the next time a version is cut.

**Comment by jarrettandrulis** [comment]
Yeah, once we get the new code up to PyPi, most of the missing Sample CIs will be fixed
