### ISSUE TITLE
Error with Sample-CI ECR PublicRepository

### ISSUE THREAD

**Issue by Gamecock** [awslabs/aws-config-rdk#342]
[Developer Guide](https://docs.aws.amazon.com/config/latest/developerguide/resource-config-reference.html#amazonelasticcontainerregistrypublic)  lists public registry as a supported type, but rdk throws an error.

```
 rdk sample-ci AWS::ECR::PublicRepository
usage: rdk sample-ci [-h] <resource type>
rdk sample-ci: error: argument <resource type>: invalid choice: 'AWS::ECR::PublicRepository' (choose from 'AWS::ApiGate
```

```rdk --version
rdk 0.8.2```

**Comment by Gamecock** [comment]
I can submit the feedback to the development guide, or submit a PR for the CLI, I just don't know which is the preferred direction.

**Comment by jarrettandrulis** [comment]
Thanks for the issue, `ECR:PublicRepository` and `ECR:Repository` are in this repo and will be included in the next version.

**Comment by mbeacom** [comment]
This is resolved.  Please try again after upgrading to the latest RDK (0.8.5).
If you encounter issues, please re-open or raise another issue.

Thanks!
