### ISSUE TITLE
Support Size and ModificationTime fields for AWS::SSM::FileData resource

### ISSUE THREAD

**Issue by dmajano** [awslabs/aws-config-rdk#343]
I'm trying to use Inventory with Config to Monitor file changes in my ec2 instances (File Integrity Monitoring) and get an alert every time a file would be changed.

At this moment, with AWS Config with resources of type **AWS::SSM::FileData**, you only can track when a file is created or deleted, but no when a file is modified because Size and Modification Time fields (From SSM Inventory) are not propagated to Config Service.

It would be nice to have this functionality supported from AWS Config Service.

**Comment by rickychau2780** [comment]
Thanks for the feedback. Would you contact the AWS support and file a ticket/request for the Config Service team?

**Comment by dmajano** [comment]
> Thanks for the feedback. Would you contact the AWS support and file a ticket/request for the Config Service team?

Thanks you for the answer. Where I can open this request? I only have Basic Support Plan in my company ATM

**Comment by rickychau2780** [comment]
For Basic support plan, you will not get technical support from the service team directly. I would recommend you to upgrade your plan, or go to the top-left question mark button in your console and click "send feedback" for feature request.

**Comment by bmorrissirromb** [comment]
Closing as this is not related to RDK functionality.
