### ISSUE TITLE
No sample CI found for AWS::S3::AccountPublicAccessBlock

### ISSUE THREAD

**Issue by JohnLakee** [awslabs/aws-config-rdk#349]
No sample CI found for AWS::S3::AccountPublicAccessBlock, even though it appears to be a supported CI.

**Comment by bmorrissirromb** [comment]
The RDK repo isn't intended to be a source of CI examples. You can see what properties are on this particular CI type in this awslabs repo: https://github.com/awslabs/aws-config-resource-schema/blob/master/config/properties/resource-types/AWS::S3::AccountPublicAccessBlock.properties.json
