### ISSUE TITLE
Invoke function locally with test event

### ISSUE THREAD

**Issue by calebworks** [awslabs/aws-config-rdk#359]
Serverless framework has a feature to invoke a Lambda function locally and pass in a test event from a local JSON file. This is really useful for local testing and fast iteration.

```
serverless invoke local --function functionName --path events/test-event.json
```

Is there any way to achieve something similar with rdk?

**Comment by bmorrissirromb** [comment]
RDK's `rdk test-local` command allows you to execute unit tests for your RDK rules. Does it meet your needs?

**Comment by bmorrissirromb** [comment]
Closing as I think RDK's unit testing framework meets this need. Let me know if you need more guidance on this, I am a big fan of RDK unit tests!
