### ISSUE TITLE
Drop supported python versions copy from rdk cli help

### ISSUE THREAD

**Issue by mbeacom** [awslabs/aws-config-rdk#364]
Per https://github.com/awslabs/aws-config-rdk/pull/362/files#r1040248774 the relayed versions of supported Python is unnecessary here and increases the burden of maintaining the module.

e.g. `help="[optional] Forces rdk deploy to use the Python(3.7-lib,3.8-lib,) lambda layer generated by rdk init --generate-lambda-layer",` would become: `help="[optional] Forces rdk deploy to use the Python lambda layer generated by rdk init --generate-lambda-layer",`

Formally proposing this be removed.

**Comment by bmorrissirromb** [comment]
This makes sense to me, though I don't know any of the background on why this was added in the first place.
