### ISSUE TITLE
Support hybrid trigger mode (both when configuration changes and periodic

### ISSUE THREAD

**Issue by rickychau2780** [awslabs/aws-config-rdk#405]

**Comment by bmorrissirromb** [comment]
Marking as low priority -- hybrid triggers are complicated and should be avoided whenever possible.

**Comment by bmorrissirromb** [comment]
Closing this issue, we explicitly advise against it in the README:
> Note that you can create rules that use EITHER resource-types OR
> maximum-frequency, but not both. We have found that rules that try to be
> both event-triggered as well as periodic wind up being very complicated
> and so we do not recommend it as a best practice.
