### ISSUE TITLE
Fix the mock dependancy on this code repo

### ISSUE THREAD

**Issue by jongogogo** [awslabs/aws-config-rdk#41]
Error from this directory code, it keeps asking for the mock. The pypi works.
From RCS Flex.

**Comment by michaelborchert** [comment]
If you use pip to install the package (even if the package is just cloned from GitHub) it should handle the dependencies automatically.  Can you provide the output of installing the package from local files and still running into issues with mock not being installed?

**Comment by jongogogo** [comment]
Closing, was not happening to me.
