### ISSUE TITLE
Incorporate Splitting of Rules/Validation when defined limit of 100 scoped resources is reached

### ISSUE THREAD

**Issue by julienbonastre** [awslabs/aws-config-rdk#411]
As per CFN doco: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-config-configrule-scope.html#cfn-config-configrule-scope-complianceresourcetypes

The limit of ComplianceResourceTypes that can be listed is 100. 

However one can generate a comma-separated string of thousands and RDK will still generate an apparent CFN template to deploy said Config Rules with, however it will fail deployment.

There is no neat/delicate way to handle this currently in RDK. We are manually carving up multiple Config Rule instances (suffixing with an number) and tying them to the same Lambda Func but with alternate scopes up to 100. Not ideal, but alas...

**Comment by rickychau2780** [comment]
Thank you! It is a limitation on AWS Config Rules. The best way for RDK to handle it, probably is the same approach. Please do file a support ticket and have the AWS Config service team to review the limit. This will help us going forward.

**Comment by bmorrissirromb** [comment]
I can add a guardrail for checking the maximum resource length...but I'm less inclined to automatically split a rule out into multiple rules automatically. It seems like it would invite a lot of complexity and downstream issues to maintain.

In RDK v0.17.0 I'm planning to add support for 'ALL' as a special resource type argument to apply a rule to all resource types. If that meets your need, I hope it can replace the manual splitting of types you're doing.

If 'ALL' doesn't meet the need, then is your workaround designed to exclude specific resource types that change (and therefore cost) a lot? If so, the Configuration Recorder can be set to exclude those types using the `exclusionByResourceTypes` key. Excluding those chatty resource types could allow you to use 'ALL'.

**Comment by bmorrissirromb** [comment]
The `ALL` option will be in #442 and I'll plan to close this issue via that PR unless told otherwise.
