### ISSUE TITLE
No sample-ci for `AWS::ElasticLoadBalancingV2::Listener`

### ISSUE THREAD

**Issue by pr3l14t0r** [awslabs/aws-config-rdk#434]
Heyho dear team! 
I wanted to create a sample-ci for the resource type `AWS::ElasticLoadBalancingV2::Listener` using the following command:

```bash
rdk sample-ci AWS::ElasticLoadBalancingV2::Listener
```

but i've received the following message: 

```text
No sample CI found for AWS::ElasticLoadBalancingV2::Listener, even though it appears to be a supported CI.  Please log an issue at https://github.com/awslabs/aws-config-rdk.
Look here: https://github.com/awslabs/aws-config-resource-schema/blob/master/config/properties/resource-types/ for additional info
```

So here i am creating an issue. :) 
I've also checked the [list of supported resource types](https://docs.aws.amazon.com/config/latest/developerguide/resource-config-reference.html#elasticloadbalancing) from AWS Config. According to that, the resource type is supported. 

Thanks in advance and kind regards,
pr3l14t0r

**Comment by bmorrissirromb** [comment]
Closed by #437
