### ISSUE TITLE
sample-ci command fails for AWS::ECS::TaskDefinition

### ISSUE THREAD

**Issue by wcannon** [awslabs/aws-config-rdk#477]
**Command Run:**  rdk sample-ci AWS::ECS::TaskDefinition                          

**Ouput:**  No sample CI found for AWS::ECS::TaskDefinition, even though it appears to be a supported CI.  Please log an issue at https://github.com/awslabs/aws-config-rdk.
Look here: https://github.com/awslabs/aws-config-resource-schema/blob/master/config/properties/resource-types/ for additional info

Creating this issue as instructed in the output.

**Comment by bmorrissirromb** [comment]
fixed in latest
