### ISSUE TITLE
`rdk deploy` fails with ` --rdklib-layer-arn`

### ISSUE THREAD

**Issue by lktslionel** [awslabs/aws-config-rdk#491]
###### GIVEN
An existing RDK lib as a lambda layer with the arn value: `<existing-rdklib-layer-arn>`
An existing RDK rule created with the runtime: `python3.11-lib `

###### WHEN
I run the following command:
```sh
rdk deploy --rdklib-layer-arn <existing-rdklib-layer-arn> \
  --functions-only \
  --all --lambda-layers <powertools-lambda-layer-arn
```

###### THEN
I get this error:

```
 Because you have selected a 'lib' runtime You may only specify 4 additional Lambda Layers.
```

#### EXPECTED RESULT

I expexted: 
* To have the layer with the specified arn `<existing-rdklib-layer-arn>` to be add as a lambda layer to my CFN template generated by the method [`__create_function_cloudformation_template`](https://github.com/awslabs/aws-config-rdk/blob/master/rdk/rdk.py#L4097).
* the resulting lambda function as a config rule has as layer member the layer with the specified `<existing-rdklib-layer-arn>`.

#### DIAGNOSTICAND PROPOSED SOLUTION

The issue come from the condition define in the following line of code https://github.com/awslabs/aws-config-rdk/blob/575cef47bcd68120c488d9a3f0806017d0838fe0/rdk/rdk.py#L3516

The condition should be written as follows:
```python
if (self.args.rdklib_layer_arn or self.args.generated_lambda_layer) and layer_count > 4:
```
because with the existing code, when you specify the rdk lib ARN the condition always evaluate to `True`.

**Comment by bmorrissirromb** [comment]
Great write-up and good catch. I'll update the logic on this one.
