### ISSUE TITLE
Add mkdocsstring plugin to RDK documentation job, if/when docstrings are used more

### ISSUE THREAD

**Issue by bmorrissirromb** [awslabs/aws-config-rdk#503]
Migrating TODOs to Issues.

```yaml
  # TODO: Enable this if/when docstrings are expanded in the core rdk module.
  # - mkdocstrings:
  #     handlers:
  #       python:
  #         paths: [rdk]
```

**Comment by pawamoy** [comment]
Hey, stalking GitHub issues -

If `rdk` is your package name, and the package is located in the root of your repository (not in a `src` folder), just don't set the `paths` option at all. This option expects search paths, so directories where packages are found, not paths to packages directly :)

**Comment by bmorrissirromb** [comment]
Oh, neat! I will just close this out then. Thanks for the tip!
