### ISSUE TITLE
Fix support for deploying in GovCloud regions

### ISSUE THREAD

**Issue by alex-mireles** [awslabs/aws-config-rdk#522]
When attempting to deploy a rule in GovCloud, during stack creation the following error is returned:

> Resource handler returned message: "Partition "aws" is not valid for resource "arn:aws:logs:*:*:log-group:/aws/lambda/RDK-Rule-Function*".

https://github.com/awslabs/aws-config-rdk/blob/543f7204cf453ececcd2d4cd3caf3c432a30cc8b/rdk/template/configRule.yaml#L281

The above line, added in the latest release, is currently breaking deployments in GovCloud. 

Should probably be using the pseudo parameter:
`Resource: "arn:${AWS::Partition}:logs:*:*:log-group:/aws/lambda/RDK-Rule-Function*"`

**Comment by bmorrissirromb** [comment]
Should be fixed now in `0.17.13`, thank you for bringing this to my attention
