### ISSUE TITLE
Getting error trying to run example in README

### ISSUE THREAD

**Issue by jebbens** [awslabs/aws-config-rdk#530]
When trying to run `rdk` to create a custom rule using the example in the README, I get the following error:

rdk create MyRule --runtime python3.12 --resource-types AWS::EC2::Instance --input-parameters '{"desiredInstanceType":"t2.micro"}'
{"desiredInstanceType":"t2.micro"}
Running create!
Error during create: can only concatenate str (not "NoneType") to str
Rolling back...
Traceback (most recent call last):
  File "/home/ec2-user/repos/pioneer/config/.venv/bin/rdk", line 8, in <module>
    sys.exit(main())
  File "/home/ec2-user/repos/pioneer/config/.venv/lib64/python3.9/site-packages/rdk/cli.py", line 48, in main
    return_val = my_rdk.process_command()
  File "/home/ec2-user/repos/pioneer/config/.venv/lib64/python3.9/site-packages/rdk/rdk.py", line 870, in process_command
    exit_code = method_to_call()
  File "/home/ec2-user/repos/pioneer/config/.venv/lib64/python3.9/site-packages/rdk/rdk.py", line 1360, in create
    raise e
  File "/home/ec2-user/repos/pioneer/config/.venv/lib64/python3.9/site-packages/rdk/rdk.py", line 1351, in create
    self.__populate_params()
  File "/home/ec2-user/repos/pioneer/config/.venv/lib64/python3.9/site-packages/rdk/rdk.py", line 3771, in __populate_params
    "CodeKey": self.args.rulename + my_session.region_name + ".zip",
TypeError: can only concatenate str (not "NoneType") to str

**Comment by bmorrissirromb** [comment]
I doubt that the rule name is the piece that's showing up as NoneType, so I'm assuming it's from the region name. You're running this from an EC2, so it should presumably *have* a region...but we're not automatically associating it.

The quick fix for you is to include the argument `--region` along with your region name of choice. That should resolve the error.

As for making this more resilient...well, we can keep this issue open.

**Comment by jebbens** [comment]
Tried that and got `rdk create: error: unrecognized arguments: --region us-east-1`. Looking in `rdk.py`, it doesn't look like `--region` is an arg for the `get_create_parser`, which is using the `get_rule_parser`. But, that tipped me off to the issue and I just set `AWS_DEFAULT_REGION` to get it to work. Initially, I skipped the `rdk init` command b/c I already have Config setup in the account and it wasn't clear to me if it would honor the existing settings or try to overwrite them with new configurations. If I had gone through that step, I would have probably figured out the region issue.

One other minor thing I noticed while processing the README - it might be helpful to define "CI" as configuration item the first time it is used in the "Edit rules locally" section.

**Comment by bmorrissirromb** [comment]
Friday-afternoon Benjamin was less than clear about this. The `--region` argument applies to the root `rdk` command, not the `create` sub-command.

`rdk --region us-east-1 create mytestrule --maximum-frequency TwentyFour_Hours` is a valid approach, though setting the default region (or running `rdk init`) would work too.
