### ISSUE TITLE
[Feature on create-rule-template] Add an option to only generate the Config Rules CFN resources

### ISSUE THREAD

**Issue by jongogogo** [awslabs/aws-config-rdk#55]
The base for Config (recorder, IAM role, bucket), might defer. It needs an option to only generate the Rule CFN.

**Comment by michaelborchert** [comment]
Do you think that should be an option in the RDK, or would it be better to just have a "RuleOnly" parameter on the generated CFN that is used to conditionally create the other resources?

**Comment by jongogogo** [comment]
Due to the size constraint of the CFn template, I would go for an option in the RDK.

**Comment by michaelborchert** [comment]
Implemented in PR #66.  Testing passed, so I will push out to PyPi along with some other features later this week.
