### ISSUE TITLE
[Feature on create-rule-template] Add rule input parameters as CFN parameters

### ISSUE THREAD

**Issue by jongogogo** [awslabs/aws-config-rdk#56]
Using the metadata of the rule, create the parameter in the CFN. We will need a mandatory vs. optional flag in the parameters.json.

**Comment by michaelborchert** [comment]
Addressed by PR #67!

Mandatory vs. Optional is determined by how input parameters are added to the Rule.  The "--input-parameters" flag is used to create required parameters (and so it is assumed that all existing rules have required parameters), and a new --optional-parameters flag allows you to specify optional inputs.  Mandatory vs. Optional is enforced on the CFN parameters, and if optional parameters are not specified in the CFN the Rule parameters are not added, as per the service team standards.

**Comment by jongogogo** [comment]
So AWESOME!

**Comment by michaelborchert** [comment]
This has been pushed to pypi, closing issue. Thanks!
