### ISSUE TITLE
[Issue on create-rule-template] Role deployed by CFN is not compatible with cross account python template

### ISSUE THREAD

**Issue by jongogogo** [awslabs/aws-config-rdk#57]
When the Global variable ASSUME_ROLE_MODE = True, the config role is being assumed by lambda in the scenario of a cross account to put-evaluation, describe, etc. 
The role config-rdk has the correct configuration (trust policy and permission policy)

**Comment by michaelborchert** [comment]
I'm not sure I understand what the problem is.  Do you mean the config-rdk role created by the create-rule-template command _does not_ have the correct configuration?  It's working for me, but I can check to see if a commit got missed on the PR.

**Comment by jongogogo** [comment]
My bad, didn't see the second statement on the Trust Policy and the ManagedPolicy. Closing....
