### ISSUE TITLE
Using the function-only without RDK init

### ISSUE THREAD

**Issue by jongogogo** [awslabs/aws-config-rdk#65]
RDK init is great for dev, but not for a consistent deployment in a Account Vending Machine context.

The Function-only is searching to use the s3 bucket: config-rule-code-bucket-XXXXXXXXXXXXXXXXXXXXX

Without RDK init, it fails (see below). Can we either create the "rdk init" bucket in function-only or specify a particular bucket to create/use : rdk deploy -f --all --s3-bucket-name blabla

```
Container] 2018/07/18 06:54:04 Running command rdk deploy -f --all
Running deploy!
Generating CloudFormation template for Lambda Functions!
Traceback (most recent call last):
  File "/usr/local/bin/rdk", line 32, in <module>
    return_val = my_rdk.process_command()
  File "/usr/local/lib/python3.6/site-packages/rdk/rdk.py", line 58, in process_command
    exit_code = method_to_call()
  File "/usr/local/lib/python3.6/site-packages/rdk/rdk.py", line 373, in deploy
    Key=self.args.stack_name + ".json"
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist
```

**Comment by PodioSpaz** [comment]
I there anything wrong with running `rdk init` against the compliance account?

**Comment by mayconfsbrito** [comment]
Thank you @PodioSpaz!
The `rdk init` command solved the problem for me.
I've changed the region between rdk init and deploy, for this reason I needed to run rdk init again, but I didn't know that.
