### ISSUE TITLE
incorrect sample ci 

### ISSUE THREAD

**Issue by sailaxman** [awslabs/aws-config-rdk#98]
the sample-ci generated by rdk for S3 resources is not the actual ci event

actual ci has preserved nested json strings for some fields such as
`"supplementaryConfiguration": {
        "AccessControlList": "{\"grantSet\":null,\"grantList\":[{\"grantee\":{\"id\":\"d609ca1050da1465c902203c3f5b8129ab754942ab2415b1cdf6de6e82c7d219\",\"displayName\":null},\"permission\":\"FullControl\"}],\"owner\":{\"displayName\":null,\"id\":\"d609ca1050da1465c902203c3f5b8129ab754942ab2415b1cdf6de6e82c7d219\"},\"isRequesterCharged\":false}",
        "BucketAccelerateConfiguration": {
            "status": null
        },
        "BucketLoggingConfiguration": {
            "destinationBucketName": null,
            "logFilePrefix": null
        },
        "BucketNotificationConfiguration": {
            "configurations": {}
        },
        "BucketPolicy": {
            "policyText": "{\"Version\":\"2012-10-17\",\"Id\":\"Policy1478390053757\",\"Statement\":[{\"Sid\":\"Stmt1478389920384\",\"Effect\":\"Deny\",\"Principal\":\"*\",\"Action\":\"s3:*\",\"Resource\":\"arn:aws:s3:::testbucket2\",\"Condition\":{\"Bool\":{\"aws:SecureTransport\":\"false\"}}},{\"Sid\":\"Stmt1478389920384\",\"Effect\":\"Allow\",\"Principal\":\"*\",\"Action\":\"s3:Get*\",\"Resource\":\"arn:aws:s3:::testbucket2\",\"Condition\":{\"StringEquals\":{\"aws:sourceVpce\":\"vpce-mock123\"}}}]}"
        }
`

but the sample-ci generates a full transformed dictionary as
`{
    "configurationItemCaptureTime": "2016-11-06T06:21:42.759Z",
    "resourceCreationTime": "2016-11-05T23:59:32.000Z",
    "availabilityZone": "Regional",
    "awsRegion": "ap-southeast-2",
    "tags": {},
    "resourceType": "AWS::S3::Bucket",
    "resourceId": "testbucket2",
    "configurationStateId": "1478413302759",
    "relatedEvents": [
        "e4a8244d-c94f-47f1-b441-424d31b0833a"
    ],
    "relationships": [],
    "arn": "arn:aws:s3:::testbucket2",
    "version": "1.2",
    "configurationItemMD5Hash": "2da1efbd2e4eee634d8be076f3e2eda7",
    "supplementaryConfiguration": {
        "BucketReplicationConfiguration": {
            "rules": {
                "testbucket2": {
                    "status": "Enabled",
                    "prefix": "",
                    "destinationConfig": {
                        "bucketARN": "arn:aws:s3:::testbucket2-us-west-2",
                        "storageClass": null
                    }
                }
            },
            "roleARN": "arn:aws:iam::264683526309:role/testbucket2-testbucket2-us-west-2-s3-repl-role"
        },
        "BucketAccelerateConfiguration": {
            "status": null
        },
        "AccessControlList": {
            "owner": {
                "displayName": "aarkho",
                "id": "28f61982c7ea8ba301f8d90b4fe979a567383f85e9706603da913d27f5522c59"
            },
            "grantSet": null,
            "isRequesterCharged": false,
            "grantList": [
                {
                    "grantee": {
                        "displayName": "aarkho",
                        "id": "28f61982c7ea8ba301f8d90b4fe979a567383f85e9706603da913d27f5522c59"
                    },
                    "permission": "FullControl"
                }
            ]
        },
        "BucketLoggingConfiguration": {
            "destinationBucketName": null,
            "logFilePrefix": null
        },
        "IsRequesterPaysEnabled": "false",
        "BucketNotificationConfiguration": {
            "configurations": {}
        },
        "BucketVersioningConfiguration": {
            "status": "Enabled",
            "isMfaDeleteEnabled": null
        },
        "BucketPolicy": {
            "policyText": {
                "Version": "2012-10-17",
                "Id": "Policy1478390053757",
                "Statement": [
                    {
                        "Resource": "arn:aws:s3:::testbucket2",
                        "Effect": "Deny",
                        "Sid": "Stmt1478389920384",
                        "Action": "s3:*",
                        "Condition": {
                            "Bool": {
                                "aws:SecureTransport": "false"
                            }
                        },
                        "Principal": "*"
                    },
                    {
                        "Resource": "arn:aws:s3:::testbucket2",
                        "Effect": "Allow",
                        "Sid": "Stmt1478389920384",
                        "Action": "s3:*",
                        "Condition": {
                            "StringEquals": {
                                "aws:sourceVpce": "vpce-unknown"
                            }
                        },
                        "Principal": "*"
                    }
                ]
            }
        }
    },
    "resourceName": "testbucket2",
    "configuration": {
        "owner": {
            "displayName": "aarkho",
            "id": "28f61982c7ea8ba301f8d90b4fe979a567383f85e9706603da913d27f5522c59"
        },
        "creationDate": "2016-11-05T23:59:32.000Z",
        "name": "testbucket2"
    },
    "configurationItemStatus": "OK",
    "accountId": "264683526309"
}`

**Comment by michaelborchert** [comment]
Fixed in v0.4.
